### ISSUE TITLE
How do I send Command from your library?

### ISSUE THREAD

**Issue by unocerobits** [gilanghamidy/heliosky-gps#1]
I am working with your excellent protocol library in a amateur project. 
I have added some functions more, per example NAV-ODO (M8U) and this is OK, but I having problems when I want to send UBX-NAV-RESETODO (0x01 0x10) type "Command" or any CFG type "Get/Set".

Can you put us a little example to do this? Thanks for your work!

**Comment by gilanghamidy** [comment]
Okay. I will prepare it and post it soon. Currently I am occupied in Tizen DevCon for few days. I will post it in my blogs when I complete it. Please hold a moment. :)

**Comment by unocerobits** [comment]
Tizen DevCon, must be genial! I touched a little the Tizen IoT with Artik in its early stage. 
I'm very interested in this project, I would be delighted to collaborate with this. 
I wait for you, BR

**Comment by gilanghamidy** [comment]
I actually checked the UBX message you expect to send, and I realized my library hasn't yet implemented sending a Command type message. I am still travelling in U.S. for the weekend so I cannot make any testing (as my workbench is in my home). But would you mind if you help me to validate something?

Does the Command message returns an ACK package or not? This will be a baseline for us to add a new method to process Command type message. I have thought how the method will be but I might not be able to validate until I get back home next Wednesday. Are you in a rush?

And one other question, does in UBX 8 protocol has Get/Set type outside of CFG family type? I only skimmed the document yesterday so I cannot check it that much.

Really appreciate your support :)

**Comment by unocerobits** [comment]
I have resolved `UBX-RESETODO` following your other NAV classes. As the type is Poll/Receive I created a new class with empty data and call it with your function `GetPollMessage<>() `

I have not been able to send `SET` type commands yet. I have some problems creating the CFG message, per example `CFG-ODO` changing Profile the Running to Car, whe I click in Send, directly send `CFG-MSG`: `B5 62 06 1E 14 00 00 00 00 00 0F 00 00 00 00 00 00 00 05 0A 00 00 99 4C 00 00 3B A0` and answered `B5 62 05 01 02 00 06 1E 2C 55 (ACK-ACK) `and then auto polling (I think to recheck the new data) with `B5 62 06 1E 00 00 24 72 +DATA + ACK-ACK `(to simplify)

How do I to create this and others CFG-MSG?

Another commands that I haven't try, it has the following behavior:
- Command `CFG-CFG` send `B5 62 06 09 0D 00 00 00 00 00 FF FF 00 00 00 00 00 00 03 1D AB` when you save config and answer `B5 62 05 01 02 00 06 09 17 40` (`ACK-ACK`)
- `UBX-RST` send `B5 62 06 04 04 00 00 00 02 00 10 68` and no receive `ACK` ( can be by reset physical interrupt)
- The `UBX-ESF` (inertial sensor) is type Get/Set but I think that is the same that Poll/Receive, per example if I poll it with `B5 62 10 02 00 00 12 46`, answer me with data OK (`B5 62 10 02 1C 00 06 29 10 00 18 20 00 00 9B 03 00 0E 98 09 00 0D 0F FD FF 05 E6 08 00 0C 06 29 10 00 48 41`). If I want to activate, send `B5 62 06 01 03 00 10 02 01 1D 74`  and the answer is `ACK-ACK` and then it starts to send data.
- For example `UBX-HNR-PVT` (`0x28 0x00`) (outside NAV) is tipe Poll/Received and its activation is `B5 62 06 01 03 00 28 00 01 33 B8` (using MSG to activate it) and answer `B5 62 05 01 02 00 06 01 0F 38` (`ACK-ACK)`

Finally, I have hard problems with dropped (or not received) packages throught Serial Com timeouts. Had you known any problem when you worked with this?

I'm happy if I can help you in something!
Thanks

**Comment by gilanghamidy** [comment]
Basically when you want to add CFG type message you have to add additional attributes of UBXConfig on the said class. Some CFG config is to enable periodic message to several message types.

To use Set command, your class currently has to have UBXConfig attribute. As long as the attribute is there, you can call it using WriteConfigAsync method.

As for the packet dropping, yes I experienced it some times but I haven't got idea how to fix it. It seems it is because of the UART behavior which has to be synchronized with the SoC baud rate, where if the SoC/RPi part hangs or lags, the GPS does not know and keep sending the data.

But that is purely my assumption because I saw this behavior when designing the auto-probing feature for baud rates, and when using UWP Serial Sample project. In my library, there has been thorough checking if the package sequence is correct or not. But perhaps I haven't implement if the package is dropped during waiting for ACK or other response message.

**Comment by unocerobits** [comment]
Well, I understand that I have to create `Set MessageType` in `UBXAttributes.cs` (my skills in C# was so basics, but I will wait your example code :)).

Respectly to Serial drop messages, I think that you. To try this, I'm testing with Teensy 3.2 microcontroller (it has hardware serial port), configuring all mesages off, only UBX-NAV-PVT over USB and UART1. With different baudrates, from 460.8k to 115.2k and RX buffers all test results was similar... I have been this conclusions:

- When rates is 1Hz, the messages that I received has a timming between 930 - 980ms = 1 msg/s --> OK
- When rates is 5Hz , all messages has average timming  of 200ms but received 4-5 msg/s --> OK in the limit
- When rate is 10Hz, the data timming in the best of cases is over 150ms, but unstable, complete msg is over 4-5msg/s.
- When rate 16Hz, GPS module hangs and autoreset. The max rate with this configuration has been 12.5Hz with 5-6 msg/s.

Also I try "Extendend TX timeout" function but I haven't checked any improvement. 
What do you think if make pollings instead wait to receive message?

Finally, I think that this change in Serial Port avoids exception crash when you have others COM devices:

 ```
//uBLOX M8 series VID/PID
 ushort vid = 0x1546;
 ushort pid = 0x01A8;    
 string aqs = SerialDevice.GetDeviceSelectorFromUsbVidPid(vid, pid);
```

PS. In debug mode, I have hundred of exceptions type `System.Threading.Task.TaskCanceledException`, can be linked to dropped messages problem?

**Comment by unocerobits** [comment]
I found the headneck for dropped packages, it's the fixed timeouts values for Serial ports. As you say in your code, timeout drops messages but this value must to be dependient of message baudrate.

I explain (if can ;)):
TEST#1 HNR-PVT - 20HZ  - 921600bps --> No 16 messages/s, only 7:
With: 
```
serialPort.WriteTimeout = TimeSpan.FromMilliseconds(100); 
serialPort.ReadTimeout = TimeSpan.FromMilliseconds(100);
CancellationTokenSource timeoutToken = new CancellationTokenSource(serialPort.ReadTimeout.Milliseconds * 10);
```
Answer:
```
GPS Time   PC Time
19:37:43  [21:37:44]  R -> UBX HNR-PVT,  Size  80,  'High Navigation Rate'
19:37:43  [21:37:44]  R -> UBX HNR-PVT,  Size  80,  'High Navigation Rate'
19:37:43  [21:37:44]  R -> UBX HNR-PVT,  Size  80,  'High Navigation Rate'
19:37:43  [21:37:44]  R -> UBX HNR-PVT,  Size  80,  'High Navigation Rate'
19:37:43  [21:37:44]  R -> UBX HNR-PVT,  Size  80,  'High Navigation Rate'
19:37:43  [21:37:44]  R -> UBX HNR-PVT,  Size  80,  'High Navigation Rate'
19:37:43  [21:37:44]  R -> UBX HNR-PVT,  Size  80,  'High Navigation Rate'
```
From 20Hz = 60ms/msg --> timeout = 50ms < 60ms/msg
Then I change to this (and try again with 9600b with same result)
```
serialPort.WriteTimeout = TimeSpan.FromMilliseconds(10); 
serialPort.ReadTimeout = TimeSpan.FromMilliseconds(10);
CancellationTokenSource timeoutToken = new CancellationTokenSource(serialPort.ReadTimeout.Milliseconds * 5);
```
Answer:
```
19:42:02  [21:42:03]  R -> UBX HNR-PVT,  Size  80,  'High Navigation Rate'
19:42:02  [21:42:03]  R -> UBX HNR-PVT,  Size  80,  'High Navigation Rate'
19:42:02  [21:42:03]  R -> UBX HNR-PVT,  Size  80,  'High Navigation Rate'
19:42:02  [21:42:03]  R -> UBX HNR-PVT,  Size  80,  'High Navigation Rate'
19:42:02  [21:42:03]  R -> UBX HNR-PVT,  Size  80,  'High Navigation Rate'
19:42:02  [21:42:03]  R -> UBX HNR-PVT,  Size  80,  'High Navigation Rate'
19:42:02  [21:42:03]  R -> UBX HNR-PVT,  Size  80,  'High Navigation Rate'
19:42:02  [21:42:03]  R -> UBX HNR-PVT,  Size  80,  'High Navigation Rate'
19:42:02  [21:42:03]  R -> UBX HNR-PVT,  Size  80,  'High Navigation Rate'
19:42:02  [21:42:03]  R -> UBX HNR-PVT,  Size  80,  'High Navigation Rate'
19:42:02  [21:42:03]  R -> UBX HNR-PVT,  Size  80,  'High Navigation Rate'
19:42:02  [21:42:03]  R -> UBX HNR-PVT,  Size  80,  'High Navigation Rate'
19:42:02  [21:42:03]  R -> UBX HNR-PVT,  Size  80,  'High Navigation Rate'
19:42:02  [21:42:03]  R -> UBX HNR-PVT,  Size  80,  'High Navigation Rate'
19:42:03  [21:42:03]  R -> UBX HNR-PVT,  Size  80,  'High Navigation Rate'
19:42:03  [21:42:03]  R -> UBX HNR-PVT,  Size  80,  'High Navigation Rate'
19:42:03  [21:42:03]  R -> UBX HNR-PVT,  Size  80,  'High Navigation Rate'
19:42:03  [21:42:03]  R -> UBX HNR-PVT,  Size  80,  'High Navigation Rate'
19:42:03  [21:42:03]  R -> UBX HNR-PVT,  Size  80,  'High Navigation Rate'
19:42:03  [21:42:03]  R -> UBX HNR-PVT,  Size  80,  'High Navigation Rate'
19:42:03  [21:42:03]  R -> UBX HNR-PVT,  Size  80,  'High Navigation Rate'
```

**Comment by gilanghamidy** [comment]
Ah I see. I was following the sample and did not think that it is linked to the timeout timespan. Please make a pull request of it and I will test the code in my place. You can add also the additional message type you have made to be included in separate commit. :)
